---
- name: put cert files
  copy:
    src: "cert/{{ item }}"
    dest: "/etc/nginx/cert/"
    owner: root
    group: root
    mode: 0644
  with_items:
    - "ecpdss.net.key"
    - "ecpdss.net.pem"
  when: ansible_distribution == 'Ubuntu' and ansible_distribution_release == 'xenial'

- name: configure virtual hosts
  template:
    src: "nginx.{{ item }}.conf.j2"
    dest: "/etc/nginx/sites-available/nginx.{{ item }}.conf"
  with_items:
   - gate
   - worker
   - admin
   - nadmin
   - plus
   - mock
   - xhprof
   - tracer
   - default
  notify: reload nginx
  when: ansible_distribution == 'Ubuntu' and ansible_distribution_release == 'xenial'

- name: configure virtual hosts
  template:
    src: "nginx.{{ item }}.conf.j2"
    dest: "/etc/nginx/conf.d/nginx.{{ item }}.conf"
  with_items:
   - plus
#   - default
  notify: reload nginx
  when: ansible_distribution == 'CentOS' and ansible_distribution_major_version == '7'

- name: configure virtual hosts for local mock
  template:
    src: "nginx.{{ item }}.conf.j2"
    dest: "/etc/nginx/sites-available/nginx.{{ item }}.conf"
  with_items:
    - "{{ external_hosts }}"
  notify: reload nginx
  when: ansible_distribution == 'Ubuntu' and ansible_distribution_release == 'xenial'

- name: disable prev sites
  file:
    path: "/etc/nginx/sites-enabled/nginx.{{ item }}.conf"
    state: absent
  with_items:
   - gate
   - worker
   - admin
   - nadmin
   - plus
   - mock
   - xhprof
   - tracer
   - default
  when: ansible_distribution == 'Ubuntu' and ansible_distribution_release == 'xenial'

- name: disable prev sites for local mock
  file:
    path: "/etc/nginx/sites-enabled/nginx.{{ item }}.conf"
    state: absent
  with_items:
    - "{{ external_hosts }}"
  when: ansible_distribution == 'Ubuntu' and ansible_distribution_release == 'xenial'

- name: enable created sites
  file:
    src: "/etc/nginx/sites-available/nginx.{{ item }}.conf"
    dest: "/etc/nginx/sites-enabled/nginx.{{ item }}.conf"
    state: link
  with_items:
   - gate
   - worker
   - admin
   - nadmin
   - plus
   - mock
   - xhprof
   - tracer
   - default
  notify:
    - reload nginx
    - restart nginx
  when: ansible_distribution == 'Ubuntu' and ansible_distribution_release == 'xenial'

- name: enable created sites for local mock
  file:
    src: "/etc/nginx/sites-available/nginx.{{ item }}.conf"
    dest: "/etc/nginx/sites-enabled/nginx.{{ item }}.conf"
    state: link
  with_items:
    - "{{ external_hosts }}"
  notify:
    - reload nginx
    - restart nginx
  when: local_mock
  when: ansible_distribution == 'Ubuntu' and ansible_distribution_release == 'xenial'
