---
- name: enable overcommit in sysctl
  sysctl:
    name: vm.overcommit_memory
    value: 1
    state: present
    reload: yes
    ignoreerrors: yes
  when: redis_travis_ci is not defined

- name: compile redis
  command: make -j{{ ansible_processor_cores + 1 }}{{ ' 32bit' if redis_make_32bit|bool else '' }}
  args:
    chdir: /usr/local/src/redis-{{ redis_version }}
    creates: /usr/local/src/redis-{{ redis_version }}/src/redis-server

- name: create redis install directory
  file:
    path: "{{ redis_install_dir }}"
    state: directory

- name: create /etc/redis
  file:
    path: /etc/redis
    state: directory

- name: check if "{{ redis.user_group }}" user exists (ignore errors)
  command: id {{ redis.user_group }}
  ignore_errors: yes
  changed_when: false
  register: user_exists

- name: add redis group
  group:
    name: "{{ redis.user_group }}"
    gid: "{{ redis.id_gid }}"
    state: present
    system: yes
  when: user_exists is failed

- name: add redis user
  user:
    name: "{{ redis.user_group }}"
    group: "{{ redis.user_group }}"
    uid: "{{ redis.id_gid }}"
    comment: "Redis"
    home: "{{ redis_install_dir }}"
    shell: /bin/false
    system: yes
  when: user_exists is failed

- name: create /var/run/redis
  file:
    path: /var/run/redis
    state: directory
    owner: "{{ redis.user_group }}"

- name: install redis
  command: make PREFIX={{ redis_install_dir }} install
  args:
    chdir: /usr/local/src/redis-{{ redis_version }}
    creates: "{{ redis_install_dir }}/bin/redis-server"

- name: list redis binaries to add to alternatives
  command: ls -1 {{ redis_install_dir }}/bin
  register: redis_binaries
  changed_when: false

- name: add redis binaries to alternatives
  alternatives:
    name: "{{ item }}"
    path: "{{ redis_install_dir }}/bin/{{ item }}"
    link: "/usr/bin/{{ item }}"
  with_items: "{{ redis_binaries.stdout_lines }}"
