---
- name: install remi repo
  yum:
    name: http://rpms.famillecollet.com/enterprise/remi-release-7.rpm
    state: present

- name: import remi GPG key
  rpm_key:
    key: http://rpms.remirepo.net/RPM-GPG-KEY-remi
    state: present

- name: import remi GPG key
  shell: "yum-config-manager --enable remi-php72"

- name: install php
  yum:
    name: php
    enablerepo: remi-php72
    state: latest

- name: install php packages
  yum:
    name: "{{ item }}"
    enablerepo: remi-php72
    state: present
  with_items: "{{ php_packages }}"
  when: php_packages is defined
  notify:
    - restart php-fpm

- name: enable php-fpm service
  service:
    name: php-fpm
    enabled: yes
