---
- name: change hostname to dev
  hostname:
    name: "{{ env_const.platform }}"
  when: inventory_hostname != 'localhost'

# - name: change hostname to dev on startup
#   template:
#     src: rc.local.j2
#     dest: /etc/rc.local
#     mode: 0755

# - name: add myself to /etc/hosts
#   lineinfile:
#     dest: /etc/hosts
#     regexp: "^127.0.0.1[ \t]+[dev\t]*localhost"
#     line: "127.0.0.1{{'\t'}}{{ env_const.platform }}{{'\t'}}localhost{{'\t'}}localhost.localdomain"
#     state: present

- set_fact:
    host_ip: '127.0.0.1'
  when: env.in_office

- set_fact:
    host_ip: '{{ env.ip }}'
  when: not env.in_office

- name: "check all hosts are set {{ host_ip }}"
  lineinfile:
    dest: /etc/hosts
    regexp: "^{{ host_ip }}[\t]+{{ env.host_prefix }}{{ item }}{{ env.host_postfix }}{{ vagrant_postfix }}"
    line: "{{ host_ip }}{{'\t'}}{{ env.host_prefix }}{{ item }}{{ env.host_postfix }}{{ vagrant_postfix }}"
  with_items:
   - "{{ host.gate }}"
   - "{{ host.worker }}"
   - "{{ host.db }}"
   - "{{ host.admin }}"
   - "{{ host.nadmin }}"
   - "{{ host.kafka01 }}"
   - "api.{{ host.terminal }}"
   - "dash.{{ host.terminal }}"
   - "pp.{{ host.terminal }}"
   - "admin.{{ host.terminal }}"
   - "sdk.{{ host.terminal }}"
   - "{{ host.plus }}"
   - "{{ host.mock }}"
   - "{{ host.xhprof }}"
   - "{{ host.tracer }}"

# - name: "check all hosts are set {{ host_ip }}"
#   lineinfile:
#     dest: /etc/hosts
#     regexp: "^{{ host_ip }}[\t]+{{ host_prefix }}{{ item.local }}{{ host_postfix }}{{ vagrant_postfix }}"
#     line: "{{ host_ip }}{{'\t'}}{{ host_prefix }}{{ item.local }}{{ host_postfix }}{{ vagrant_postfix }} {{ item.remote }}"
#   with_items:
#    - { local: "{{ host_gate }}", remote: "front01.qa.ams front01.dev.ams" }
#    - { local: "{{ host_mock }}", remote: "mock01.ecpdss.net mock01.qa.ams mock.dev" }
#   when: local_mock

# - name: "check all DWH hosts are set {{ host_ip }}"
#   lineinfile:
#    dest: /etc/hosts
#    regexp: "^{{ dwh_host_ip }}[\t]+{{ item }}"
#    line: "{{ dwh_host_ip }}{{'\t'}}{{ item }}"
#    state: present
#   with_items:
#    - "{{ host_bi }}"
#    - "{{ host_bi_api }}"
#   when: use_dwh
