---
- name: install ansible custom fact file
  copy:
    src: installed.fact
    dest: /etc/ansible/facts.d/
    directory_mode: 0755
    force: no

- name: display all variables/facts known for a host
  debug:
    var: "{{ hostvars[inventory_hostname] }}"
    verbosity: 3

# - name: Add EPEL repository
#   yum_repository:
#     name: epel-repo
#     description: EPEL YUM repo
#     gpgkey: https://download.fedoraproject.org/pub/epel/RPM-GPG-KEY-EPEL-7
#     baseurl: https://download.fedoraproject.org/pub/epel/7/x86_64/

# - name: update apt cache (yum check-update)
#   yum:
#     name: "*"
#     state: latest
#     update_cache: yes

- name: ensure system packages are installed
  yum:
    update_cache: yes
    name: "{{ item }}"
    state: present
  with_items:
    - automake
    - autoconf
    - curl
    - wget
    - htop
    - mc
    - zip
    - unzip
    - nano
    - git
    - epel-release
    - openssl
    - openssl-devel
    - libsigc++20-devel
    - nano
    - sendmail
    - tmux
    - cmake
    - vim
    - traceroute
    - python-pip
    - yum-utils
    - net-tools
    # - subscription-manager
    # - golang
    # - locales
    # - pkg-config
    # - build-essential
    # - python-software-properties
    # - software-properties-common
    # - python-mysqldb
    # - python-psycopg2
    # - redis-tools
    # - lsb-core
    # - apt-transport-https
    # - nfs-common

# - name: add nodejs official apt repository and key
#   shell: "wget -qO- https://deb.nodesource.com/setup_8.x | bash - warn=no"

# - name: update apt
#   apt:
#     update_cache: yes

# - name: install nodejs
#   apt:
#     name: nodejs
#     state: present

# - name: install npm packages
#   npm:
#     name: "{{ item }}"
#     global: yes
#   with_items:
#     - bower
#     - less

# - name: add yarn official apt repository
#   apt_repository:
#     repo: "deb https://dl.yarnpkg.com/debian/ stable main"
#     state: present

# - name: add yarn key
#   apt_key:
#     url: https://dl.yarnpkg.com/debian/pubkey.gpg
#     state: present

# - name: manually update apt-key
#   apt:
#     update_cache: yes

# - name: install yarn
#   apt:
#     name: yarn
#     state: present

- name: pam_limits remove default
  shell: |
    if [ -n "$(ls -A /etc/security/limits.d/ 2>/dev/null)" ]; then
        rm -rf /etc/security/limits.d/*
    fi
  args:
    executable: /bin/bash
  register: shell_res
  changed_when: false

- name: pam_limits
  pam_limits:
    domain: "{{ item.domain }}"
    limit_type: "-"
    limit_item: "{{ item.item }}"
    value: "{{ item.value }}"
  with_items:
    - { domain: 'root', item: 'nofile', value: '1048576' }
    - { domain: '*', item: 'nofile', value: '1048576' }
    - { domain: 'root', item: 'nproc', value: 'unlimited' }
    - { domain: '*', item: 'nproc', value: 'unlimited' }
    - { domain: 'root', item: 'stack', value: 'unlimited' }
    - { domain: '*', item: 'stack', value: 'unlimited' }

- name: pam_limits to system-auth
  lineinfile:
    dest: /etc/pam.d/system-auth
    regexp: "session.*required.*pam_limits.so"
    line: "session     required      pam_limits.so"

- name: get services owner by "{{ nginx_fpm.user_group }}"
  shell: "systemctl list-unit-files | grep -oE 'php-fpm.service|nginx.service'"
  register: www_services
  failed_when: www_services.rc == 2

- name: stop services owner by "{{ nginx_fpm.user_group }}"
  service:
    name: "{{ item }}"
    state: stopped
  with_items:
    - "{{ www_services.stdout }}"
  when: www_services.rc == 0

- name: add group "{{ nginx_fpm.user_group }}"
  group:
    name: "{{ nginx_fpm.user_group }}"
    gid: "{{ nginx_fpm.id_gid }}"
    state: present

- name: add user "{{ nginx_fpm.user_group }}"
  user:
    name: "{{ nginx_fpm.user_group }}"
    group: "{{ nginx_fpm.user_group }}"
    uid: "{{ nginx_fpm.id_gid }}"
    create_home: no
    system: yes

- name: add deployer_user to "{{ nginx_fpm.user_group }}"
  user:
    name: "{{ env.username }}"
    append: yes
    groups: "{{ nginx_fpm.user_group }}"

# - name: locale gen
#   locale_gen:
#     name: en_US.UTF-8
#     state: present

- name: disabling selinux
  selinux:
    state: disabled

