---
- name: install ansible custom fact file
  template:
    src: installed.fact
    dest: /etc/ansible/facts.d/
    directory_mode: 0755
    force: no

# - name: Add EPEL repository
#   yum_repository:
#     name: epel-repo
#     description: EPEL YUM repo
#     gpgkey: https://download.fedoraproject.org/pub/epel/RPM-GPG-KEY-EPEL-7
#     baseurl: https://download.fedoraproject.org/pub/epel/7/x86_64/

- name: ensure system packages are installed
  yum:
    update_cache: yes
    name: "{{ item }}"
    state: present
  with_items:
    - automake
    - autoconf
    - curl
    - wget
    - htop
    - mc
    - zip
    - unzip
    - nano
    - git
    - epel-release
    - openssl
    - openssl-devel
    - libsigc++20-devel
    - nano
    # - sendmail
    - tmux
    - cmake
    - vim
    - traceroute
    - python-pip
    - yum-utils
    - net-tools
    # - subscription-manager
    # - golang
    # - locales
    # - pkg-config
    # - build-essential
    # - python-software-properties
    # - software-properties-common
    # - python-mysqldb
    # - python-psycopg2
    # - redis-tools
    # - lsb-core
    # - apt-transport-https
    # - nfs-common
    - centos-release-scl
    - nmap-ncat
    - MySQL-python

- name: install gcc 5.3.1
  yum:
    update_cache: yes
    name: "{{ item.name }}"
    state: "{{ item.state }}"
  with_items:
    - { name: 'devtoolset-4-gcc', state: 'present' }
    - { name: 'devtoolset-4-gcc-c++', state: 'present' }

- name: configure gcc 5.3.1
  alternatives:
    name: "{{ item.name }}"
    link: "{{ item.link }}"
    path: "{{ item.path }}"
    priority: "{{ item.priority }}"
  with_items:
    - { name: 'gcc', link: '/usr/bin/gcc', path: '/opt/rh/devtoolset-4/root/usr/bin/gcc', priority: '50' }
    - { name: 'g++', link: '/usr/bin/g++', path: '/opt/rh/devtoolset-4/root/usr/bin/g++', priority: '50' }
    - { name: 'cpp', link: '/usr/bin/cpp', path: '/opt/rh/devtoolset-4/root/usr/bin/cpp', priority: '50' }
    - { name: 'c++', link: '/usr/bin/c++', path: '/opt/rh/devtoolset-4/root/usr/bin/c++', priority: '50' }

- name: upgrade pip
  shell: "pip install --upgrade pip"

# - name: add nodejs official apt repository and key
#   shell: "wget -qO- https://deb.nodesource.com/setup_8.x | bash - warn=no"

# - name: update apt
#   apt:
#     update_cache: yes

# - name: install nodejs
#   apt:
#     name: nodejs
#     state: present

# - name: install npm packages
#   npm:
#     name: "{{ item }}"
#     global: yes
#   with_items:
#     - bower
#     - less

# - name: add yarn official apt repository
#   apt_repository:
#     repo: "deb https://dl.yarnpkg.com/debian/ stable main"
#     state: present

# - name: add yarn key
#   apt_key:
#     url: https://dl.yarnpkg.com/debian/pubkey.gpg
#     state: present

# - name: manually update apt-key
#   apt:
#     update_cache: yes

# - name: install yarn
#   apt:
#     name: yarn
#     state: present

- name: pam_limits remove default
  shell: |
    if [ -n "$(ls -A /etc/security/limits.d/ 2>/dev/null)" ]; then
        rm -rf /etc/security/limits.d/*
    fi
  args:
    executable: /bin/bash
  register: shell_res
  changed_when: false

- name: pam_limits
  pam_limits:
    domain: "{{ item.domain }}"
    limit_type: "-"
    limit_item: "{{ item.item }}"
    value: "{{ item.value }}"
  with_items:
    - { domain: 'root', item: 'nofile', value: '1048576' }
    - { domain: '*', item: 'nofile', value: '1048576' }
    - { domain: 'root', item: 'nproc', value: 'unlimited' }
    - { domain: '*', item: 'nproc', value: 'unlimited' }
    - { domain: 'root', item: 'stack', value: 'unlimited' }
    - { domain: '*', item: 'stack', value: 'unlimited' }

- name: pam_limits to system-auth
  lineinfile:
    dest: /etc/pam.d/system-auth
    regexp: "session.*required.*pam_limits.so"
    line: "session     required      pam_limits.so"

- name: get services owner by "{{ nginx_fpm.user_group }}"
  shell: "systemctl list-unit-files | grep -oE 'php[0-7|-]+.*.service|nginx.service'"
  register: www_services
  failed_when: www_services.rc == 2

- name: stop services owner by "{{ nginx_fpm.user_group }}"
  service:
    name: "{{ item }}"
    state: stopped
  with_items:
    - "{{ www_services.stdout_lines }}"
  when: www_services.rc == 0

- name: add group "{{ nginx_fpm.user_group }}"
  group:
    name: "{{ nginx_fpm.user_group }}"
    gid: "{{ nginx_fpm.id_gid }}"
    state: present

- name: add user "{{ nginx_fpm.user_group }}"
  user:
    name: "{{ nginx_fpm.user_group }}"
    group: "{{ nginx_fpm.user_group }}"
    uid: "{{ nginx_fpm.id_gid }}"
    create_home: no
    system: yes

- name: add "{{ env_const.username }}" to "{{ nginx_fpm.user_group }}"
  user:
    name: "{{ env_const.username }}"
    append: yes
    groups: "{{ nginx_fpm.user_group }}"

# - name: locale gen
#   locale_gen:
#     name: en_US.UTF-8
#     state: present

- name: disabling selinux
  selinux:
    state: disabled

- name: add /usr/local/lib for ldconfig
  template:
    src: usr-local-lib.conf
    dest: /etc/ld.so.conf.d/
    directory_mode: 0755

- name: invoke ldconfig
  shell: "ldconfig"

- name: add PATH /usr/local/bin to /etc/profile
  lineinfile:
    path: "/etc/profile"
    line: "export PATH=\"/usr/local/bin:$PATH\""

###########
### ansible
###########
- name: update apt cache (yum check-update/yum update)
  yum:
    name: "*"
    state: latest
    update_cache: yes

- name: display all variables/facts known for a host
  debug:
    var: "{{ hostvars[inventory_hostname] }}"
    verbosity: 3

# - name: install setlock
#   apt:
#    name: "daemontools"
#    state: present
