---
- name: remove prev jaeger binaries and UI
  file:
    path: "{{ path.root_dir }}/ansible-packer/tools/tracer/bin"
    state: absent

- name: get jaeger binaries and UI
  git:
    repo: git@github.com:vadbes46/jaeger-build.git
    dest: "{{ path.root_dir }}/ansible-packer/tools/tracer/bin"
    version: master
    update: yes
    accept_hostkey: yes
  become: yes
  become_user: "{{ env.username }}"
