---
php_packages:
  - php-bcmath
  - php-cli
  - php-common
  - php-devel
  - php-fpm
  - php-gd
  - php-intl
  - php-json
  - php-mbstring
  - php-mysqlnd
  - php-odbc
  - php-pdo
  - php-pecl-gearman
  - php-pecl-memcached
  - php-pecl-zip
  - php-soap
  - php-xml

php_extension_conf_paths:
  - /etc/php-fpm.d
  - /etc/php.d

ext_workspace: "/home/vagrant"